ALTER TABLE assets ADD COLUMN IF NOT EXISTS bond_purchase_value NUMERIC(19,2);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS bond_gross_value NUMERIC(19,2);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS bond_taxable_gain NUMERIC(19,2);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS bond_tax_rate NUMERIC(7,4);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS bond_tax_amount NUMERIC(19,2);
