package com.freedom.freedom_backend.asset;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

public record AssetResponse(
        Long id,
        String name,
        BigDecimal value,
        String color,
        AssetCategory category,
        String iconKey,
        boolean systemCash,
        Long portfolioId,
        boolean marketPriced,
        MetalSymbol metalSymbol,
        BigDecimal metalQuantity,
        MetalUnit metalUnit,
        BigDecimal marketPriceUsd,
        BigDecimal usdPlnRate,
        Instant marketUpdatedAt,
        RealEstateType realEstateType,
        String realEstateCity,
        String realEstateDistrict,
        BigDecimal realEstateAreaSqm,
        RealEstateValuationMode realEstateValuationMode,
        RealEstateMarketSegment realEstateMarketSegment,
        BigDecimal realEstatePurchasePrice,
        LocalDate realEstatePurchaseDate,
        BigDecimal realEstateMedianPriceSqm,
        BigDecimal realEstateEstimatedPriceSqm,
        String realEstateScope,
        String realEstateResolvedArea,
        Integer realEstateRecordCount,
        LocalDate realEstatePeriodFrom,
        LocalDate realEstatePeriodTo,
        BigDecimal realEstateAnchorMedianPriceSqm,
        BigDecimal realEstateQualityFactor,
        String realEstateAnchorResolvedArea,
        String realEstateAnchorScope,
        Integer realEstateAnchorRecordCount,
        LocalDate realEstateAnchorPeriodFrom,
        LocalDate realEstateAnchorPeriodTo,
        Instant realEstateUpdatedAt
) {
    public static AssetResponse from(Asset a) {
        return new AssetResponse(
                a.getId(),
                a.getName(),
                a.getValue(),
                a.getColor(),
                a.getCategory(),
                a.getIconKey(),
                a.isSystemCash(),
                a.getPortfolioId(),
                a.isMarketPriced(),
                a.getMetalSymbol(),
                a.getMetalQuantity(),
                a.getMetalUnit(),
                a.getMarketPriceUsd(),
                a.getUsdPlnRate(),
                a.getMarketUpdatedAt(),
                a.getRealEstateType(),
                a.getRealEstateCity(),
                a.getRealEstateDistrict(),
                a.getRealEstateAreaSqm(),
                a.getRealEstateValuationMode(),
                a.getRealEstateMarketSegment(),
                a.getRealEstatePurchasePrice(),
                a.getRealEstatePurchaseDate(),
                a.getRealEstateMedianPriceSqm(),
                a.getRealEstateEstimatedPriceSqm(),
                a.getRealEstateScope(),
                a.getRealEstateResolvedArea(),
                a.getRealEstateRecordCount(),
                a.getRealEstatePeriodFrom(),
                a.getRealEstatePeriodTo(),
                a.getRealEstateAnchorMedianPriceSqm(),
                a.getRealEstateQualityFactor(),
                a.getRealEstateAnchorResolvedArea(),
                a.getRealEstateAnchorScope(),
                a.getRealEstateAnchorRecordCount(),
                a.getRealEstateAnchorPeriodFrom(),
                a.getRealEstateAnchorPeriodTo(),
                a.getRealEstateUpdatedAt()
        );
    }
}
